[package]
name = "hop"
version = "0.1.0"
edition = "2021"

[dependencies]

dirs = "4.0"
regex = "1.5"
console = "0.15"
tokio-tar = "0.3"
gitignore = "1.0"
dialoguer = "0.10"
webbrowser = "0.7"
portpicker = "0.1"
serde_yaml = "0.8"
serde_json = "1.0"
serde_repr = "0.1"
futures-util = "0.3"
clap = { version = "3.2", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
hyper = { version = "0.14", features = ["server"] }
reqwest = { version = "0.11", features = ["json", "multipart"] }
tokio-tungstenite = { version = "0.17", features = ["native-tls"] }
async-compression = { version = "0.3", features = ["tokio", "gzip", "zlib"] }
