[package]
name = "hop"
version = "0.1.3"
edition = "2021"

[dependencies]
log = "0.4"
dirs = "4.0"
regex = "1.5"
ignore = "0.4"
console = "0.15"
tokio-tar = "0.3"
dialoguer = "0.10"
webbrowser = "0.7"
portpicker = "0.1"
serde_yaml = "0.8"
serde_json = "1.0"
serde_repr = "0.1"
futures-util = "0.3"
clap = { version = "3.2", features = ["derive"] }
fern = { version = "0.6", features = ["colored"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
hyper = { version = "0.14", features = ["server"] }
async-compression = { version = "0.3", features = ["tokio", "gzip", "zlib"] }
reqwest = { version = "0.11", features = [
    "json",
    "multipart",
    "rustls-tls-native-roots",
] }
tokio-tungstenite = { version = "0.17", features = ["rustls-tls-native-roots"] }
